[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "generand"
version = "0.0.1"
authors = [
  { name="rajat maheshwari", email="rajt.maheshwari30@gmail.com" },
]
description = "A package to generate random numbers from various distributions"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/pypa/generand"
"Bug Tracker" = "https://github.com/pypa/generand/issues"