[tool.isort]
profile = "black"

[tool.poetry]
name = "python-regius"
version = "0.2.0"
description = "Python Regius - A simple & friendly Python RPC framework."
authors = ["王见充 <gerhut@sya.org.cn>"]
license = "Proprietary"
readme = "README.md"
repository = "https://jihulab.com/Sya/Regius/regius.git"

[[tool.poetry.packages]]
include = "regius"

[tool.poetry.dependencies]
python = "^3.11"
httpx = "^0.23.0"
sanic = "^23.3.0"
python-dotenv = "^1.0.0"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
flake8 = "^6.0.0"
isort = "^5.12.0"
pytest = "^7.3.1"
pytest-asyncio = "^0.21.0"
pytest-cov = "^4.0.0"
pytest-httpx = "^0.21.3"
sanic-testing = "^23.3.0"

[tool.poetry.scripts]
test = "pytest:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
