[tool.poetry]
name = "charsi"
version = "2.0.0"
description = "A command-line tool to help game modders build string resources for Diablo II: Resurrected."
authors = ["HE Yaowen <he.yaowen@hotmail.com>"]
license = "GPL-3.0"
readme = "README.md"
homepage = "https://github.com/he-yaowen/charsi"
packages = [{include = "charsi", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
click = "^8.1.3"
lupa = "^1.14.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.2.2"
pyinstaller = "^5.10.1"
pylint = "^2.17.2"
pytest = "^7.3.1"
pytest-mock = "^3.10.0"
pytest-cov = "^4.0.0"

[tool.poetry.scripts]
charsi = "charsi.__main__:cli"

[tool.poe.tasks]
dist = "poetry run pyinstaller charsi.spec"
init = {shell ="poetry install && poetry run pre-commit install"}
lint = "poetry run pylint src"
publish = {shell ="poetry build && poetry publish"}
test = "poetry run pytest --cov=src --cov-report=term-missing"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
