[tool.poetry]
name = "dfsjson"
version = "1.0.11"
description = "A robust JSON encoder that fixes errors by utilizing DFS algorithm."
authors = ["Unsal Gokdag <unsal.gokdag@gmail.com>"]
readme = "README.md"
packages = [{include = "dfsjson"}]
keywords = ["JSON","JSON Serialize", "DFS", "Error correcting JSON"]
homepage = "https://github.com/AutomaticHourglass/dfsjson"

[tool.poetry.dependencies]
python = "^3.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
