[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "webauto_hj3415"
version = "0.1.2"
authors = [
  { name="Hyungjin Kim", email="hj3415@gmail.com" },
]
description = "Gathering the stock data"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "util_hj3415>=0.9.6",
    "selenium>=4.8.3",
    "2captcha-python>=1.2.0"
]

# cli script 만드는 방법
# https://hatch.pypa.io/latest/config/metadata/
# https://dev.to/thefern/argparse-and-script-entry-points-4cde
[project.scripts]
ecolian = "webauto_hj3415.cli:ecolian_cli"

[project.urls]
"Homepage" = "https://pypi.org/project/webauto_hj3415/"
"Bug Tracker" = "https://pypi.org/project/webauto_hj3415/"