[tool.poetry]
name = "crispr-library-prep"
version = "0.1.8"
description = ""
authors = ["Basheer Becerra <bbecerr@outlook.com>"]
readme = "README.md"
packages = [{include = "crispr_library_prep"}]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
numpy = "^1.23"
scipy = "^1.10.1"
matplotlib = "^3.7.1"
biopython = "^1.81"
typeguard = "^3.0.2"
pandas = "^1.5.3"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
