[tool.poetry]
name = "shp2metric"
version = "1.3.4"
description = "Converts Operations Center shapefiles to metric"
authors = ["Jo√£o Fauvel <jmmfauvel@gmail.com>"]
readme = "README.md"
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.8"
geopandas = "^0.12.2"
typer = "^0.7.0"
rich = "^13.3.4"
fiona = "^1.9.3"

[tool.poetry.scripts]
shp2metric = "shp2metric.main:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
