[tool.poetry]
name = "trailwatch"
version = "0.3.0"
description = "Python SDK for TrailWatch by Kicksaw"
license = "Apache-2.0"
authors = ["George Bocharov <george@kicksaw.com>"]
readme = "README.md"
homepage = "https://www.kicksaw.com/"
repository = "https://github.com/Kicksaw-Consulting/trailwatch-python-sdk"
packages = [
    { include = "trailwatch", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.2"
simple-salesforce = { version = "^1.12.3", optional = true }

[tool.poetry.extras]
salesforce = ["simple-salesforce"]

[tool.poetry.group.development.dependencies]
pre-commit = "*"

[tool.poetry.group.lint.dependencies]
black = "*"
pylint = "*"
flake8 = "*"
mypy = "*"
isort = "*"
bandit = { extras = ["toml"], version = "*" }

[tool.poetry.group.test.dependencies]
pytest = "*"
pytest-cov = "*"
responses = "*"

[tool.poetry.group.typing.dependencies]
types-requests = "^2.28.11.5"
types-python-dateutil = "^2.8.19.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# Development tool configuration

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
lines_between_types = 1

[tool.bandit]
exclude_dirs = ["tests", "scripts"]
skips = [
    "B101",  # assert statement
]

[tool.pylint.'MASTER']
fail-under = 1.0

[tool.pylint.'MESSAGES CONTROL']
disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "too-few-public-methods",
    "useless-super-delegation",
    "too-many-lines",
    "too-many-branches",
    "too-many-statements",
]

[tool.pylint.'FORMAT']
max-line-length = 88

[tool.pytest.ini_options]
addopts = "-v --cov=trailwatch --cov-report=term --cov-report=xml --cov-report=html"
testpaths = [
    "tests",
]

[tool.coverage.report]
exclude_lines = [
    'pragma: no cover',
    'raise AssertionError',
    'raise NotImplementedError',
    'if __name__ == .__main__.:',
    'def __repr__',
]
omit = [
    "tests/*",
]
precision = 1
skip_empty = true
sort = "-Cover"
