[tool.poetry]
name = "notpy"
version = "0.0.4"
description = "Create/Delete files and edit them as markdown files in neovim"
authors = ["jontok <jonas@tokmaji.de>"]
license = "GPL-3.0-only"
readme = "README.md"
packages = [
    {include = "notpy"},
]
homepage = "https://github.com/jontok/Notpy"
repository = "https://github.com/jontok/Notpy"
documentation = "https://github.com/jontok/Notpy/blob/master/README.md"
keywords=["notes","markdown","python","nvim","neovim"]
classifiers=[
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
    'Programming Language :: Python :: 3.10',
]

[tool.poetry.scripts]
notpy = 'notpy:notpy.main'


[tool.poetry.dependencies]
python = "^3.10"
markdown = "3.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
