[project]
name = "python-orbuculum-bad"
version = "0.1.3"
description = "A really solo and ungly client for orbuculum service."
authors = [
    { name = "ssfdust", email = "ssfdust@gmail.com" }
]
dependencies = ["grpc_requests~=0.1.10"]
readme = "README.md"
requires-python = ">= 3.7"
license = { text = "MIT" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
ifconfig = "orbuculum_bad.cli:ifconfig"

[tool.rye]
managed = true
dev-dependencies = ["build~=0.10.0", "twine~=4.0.2"]
