[tool.poetry]
name = "dai-python-commons"
version = "4.14.0"
description = "Collection of small python utilities useful for lambda functions or glue jobs. By the Stockholm Public Transport Administration."
authors = []

[tool.poetry.dependencies]
python = "~3.8"
loguru = "^0.6.0"
boto3 = "1.26.99"
pyarrow = { version = "7.0.0", optional = true }
s3fs = { version = "0.4.2", optional = true }
awswrangler = { version = "3.0.0", optional = true }
boto3-stubs = { version = "1.26.99", extras = ["s3", "glue"] }
cryptography = { version = "38.0.1", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^5.2"
moto = "^1.3"
pylint = "^2.13.5"


[tool.poetry.extras]
data-consolidation = ["s3fs", "pyarrow"]
glue = ["awswrangler", "cryptography"]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = [
  "."
]