[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vidis_algorithms_api"
version = "0.4.4"
authors = [
    { name="Mukhin Artem", email="artemmukhinssau@gmail.com" },
]
description = "The API for defining an algorithm has to be used in the 'Vidis'"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages]
find = {}
