[build-system]
requires = ["setuptools>=67.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bns_utils"
version = "0.0.3"
authors = [
  { name="Example Author", email="author@example.com" },
]
description = "Some utilities for BNS internal use"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    'cycler >= 0.11.0, < 1',
    'matplotlib >= 3.5.0, < 5',
    'tqdm >= 4.64.0, < 5',
    'pandas >= 1.5.0, < 2',
    'scipy >= 1.9.0, < 2'
]

[project.urls]
"Homepage" = "https://github.com/Dave-the-python-developer/BNS_utils"
"PyPi" = "https://pypi.org/project/bns-utils/"

[tool.pytest.ini_options]
pythonpath = [
  "src"
]