[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "NeuralBasics"
version = "1.0.16"
authors = [
  { name="Henry Cook", email="henryscookolaizola@gmail.com" },
]
description = "Neural network basics module. Number detection on images."
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/HCook86/NeuralBasics"
"Bug Tracker" = "https://github.com/HCook86/NeuralBasics/issues"