[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "auraboros"
version = "0.19.0-alpha"
dependencies = ["pygame", "moderngl"]
requires-python = ">=3.10.8"

# [tool.hatch.build]
