[tool.poetry]
name = "dfa-mutate"
version = "0.1.0"
description = "Library for mutating a DFA represented using the dfa library."
authors = ["Marcell Vazquez-Chanlatte <mvc@linux.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "dfa_mutate", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
dfa = "^4.6.3"
numpy = {version = "^1.24.3", optional = true}

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
numpy = "^1.24.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
