[tool.poetry]
name = "unwanted-content-detector"
version = "0.1.6"
description = "A library to detect undesired, unbranded, or harmful content"
authors = ["Jean Carlo Machado <jean.machado@getyourguide.com>"]
license = "Apache"
readme = "README.md"
packages = [{include = "unwanted_content_detector"}]

[tool.poetry.dependencies]
python = "^3.9"
fire = "^0.5.0"
pandas = "^2.0.0"
transformers = "^4.28.0"
evaluate = "^0.4.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.0"
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
unwanted_detector = 'cli:main'
