[tool.poetry]
name = "bytecli"
version = "0.1.0"
description = ""
authors = ["Allan <allanklp@gmail.com>"]
readme = "README.md"
packages = [{include = "bytecli"}]

[tool.poetry.scripts]
bytecli = "bytecli.main:app"

[tool.poetry.dependencies]
python = "^3.10"

ipdb = "^0.13.13"
requests = "^2.28.2"
isort = "^5.12.0"
black = "^23.3.0"
rich = "^13.3.4"
typer = "^0.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
