[tool.poetry]
name = "stdlibby-py"
version = "0.5.10"
description = ""
authors = ["00il <git@00il.com>"]
readme = "README.md"
packages = [
		 {include = "stdlibby_py/*.py"},
]

[tool.poetry.dependencies]
python = "^3.10"
orjson = "^3.8.9"
inquirer = "^3.1.3"
pydantic = "^1.10.7"
aioconsole = "^0.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
