[tool.poetry]
name = "leaguedaily"
version = "0.1.0"
description = "League of Legends Esports results from your terminal!"
authors = ["Hieu Vuong <tvuong5@dons.usfca.edu>"]
readme = "README.md"
packages = [
    {include = "src"}
]

[tool.poetry.scripts]
league-daily = "src.main:app"

[tool.poetry.dependencies]
python = "^3.10"
typer = "0.7.0"
certifi = "2022.12.7"
charset-normalizer = "3.1.0"
click = "8.1.3"
colorama = "0.4.6"
commonmark = "0.9.1"
idna = "3.4"
mwclient = "0.10.1"
oauthlib = "3.2.2"
pygments = "2.14.0"
pytz = "2022.7.1"
pytz-deprecation-shim = "0.1.0.post0"
requests = "2.28.2"
requests-oauthlib = "1.3.1"
rich = "12.6.0"
shellingham = "1.5.0.post1"
six = "1.16.0"
tzdata = "2022.7"
tzlocal = "4.2"
urllib3 = "1.26.15"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

