[tool.poetry]
authors = [
  "Timo P. Gros <timopgros@cs.uni-saarland.de>",
  "Joschka Gro√ü <jgross@cs.uni-saarland.de>"
]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Operating System :: OS Independent",
]
description = "Python Simulation of the Racetrack game. This implementation is compatible with the OpenAI Gym API, and comes with additional extensions"
name = "racetrackgym"
readme = "README.md"
version = "0.2.5"

[tool.poetry.dependencies]
Pillow = "^8.4.0"
argparse = "^1.4.0"
matplotlib = "^3.4.3"
numpy = "^1.21.4"
python = ">=3.9,<3.11"
rlmate = ">=0.0.20"
jupyterlab = "^3.6.3"

[tool.poetry.dev-dependencies]
black = {version = "*", allow-prereleases = true}
flake8 = "^3.7.9"
flake8-bugbear = "^20.1.2"
pep8-naming = "^0.9.1"
pytest = "^6.2.5"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
